import { type Doc, isGate, isSequential, nodeTitle, specOf } from "./circuit";
import { CATALOG } from "./catalog";
import { GRID_SIZE, snapToGrid, generateUniqueId } from "./geometry";
import type { CNode, NodeKind, Wire } from "./types";

// ---------------------------------------------------------------------------
// Helpers for Verilog emission
// ---------------------------------------------------------------------------

function sanitizeIdentifier(raw: string) {
  let t = raw.replace(/[^A-Za-z0-9_]/g, "_");
  if (!t) t = "n";
  if (/^[0-9]/.test(t)) t = "n_" + t;
  return t;
}

function generateUniqueName(base: string, used: Set<string>) {
  let s = sanitizeIdentifier(base);
  let i = 2;
  while (used.has(s)) s = `${sanitizeIdentifier(base)}_${i++}`;
  used.add(s);
  return s;
}

function getOrCreateNetIdentifier(nodeId: string, port: number, used: Set<string>, cache: Map<string, string>, hint: string) {
  const k = `${nodeId}:${port}`;
  const hit = cache.get(k);
  if (hit) return hit;
  const name = generateUniqueName(hint, used);
  cache.set(k, name);
  return name;
}

// ---------------------------------------------------------------------------
// Emit Verilog (Circuit IR -> HDL)
// Includes a LOGICFORGE IR comment block for lossless round-trip.
// ---------------------------------------------------------------------------

export function generateVerilog(doc: Doc): string {
  const { nodes, wires, defs } = doc;
  const used = new Set<string>(["module", "input", "output", "wire", "assign", "always", "begin", "end", "posedge"]);
  const cache = new Map<string, string>();
  const title = (nId: string) => {
    const n = nodes.find((x) => x.id === nId);
    return n ? nodeTitle(n, defs) : nId;
  };

  const inputs = nodes.filter((n) => n.type === "INPUT" || n.type === "CLOCK");
  const outputs = nodes.filter((n) => n.type === "OUTPUT" || n.type === "LED");

  for (const n of nodes) {
    const sp = specOf(n, defs);
    sp.outs.forEach((nm, i) => getOrCreateNetIdentifier(n.id, i, used, cache, `${title(n.id)}_${nm}`));
    if (n.type === "INPUT" || n.type === "CLOCK") getOrCreateNetIdentifier(n.id, 0, used, cache, title(n.id));
  }

  const inPorts = inputs.map((n) => getOrCreateNetIdentifier(n.id, 0, used, cache, title(n.id)));
  const outPorts = outputs.map((n) => {
    const nm = generateUniqueName(title(n.id) + "_o", used);
    cache.set(`probe:${n.id}`, nm);
    return nm;
  });

  const portList = [...inPorts.map((p) => `  input  ${p}`), ...outPorts.map((p) => `  output ${p}`)].join(",\n");
  const lines: string[] = [];
  const mod = sanitizeIdentifier(doc.name || "LogicForge");
  // IR block for lossless parse: single JSON line per comment
  // Keep it at the very top so the parser can find it quickly.
  try {
    const ir = JSON.stringify(doc);
    lines.push(`// LOGICFORGE_BEGIN`);
    lines.push(`// ${ir}`);
    lines.push(`// LOGICFORGE_END`);
  } catch {
    // ignore
  }
  lines.push(`// Generated by LogicForge`);
  lines.push(`module ${mod} (`);
  lines.push(portList || "  // no ports");
  lines.push(");");
  lines.push("");

  const driven = new Set(inPorts);
  for (const n of nodes) {
    const sp = specOf(n, defs);
    for (let i = 0; i < sp.outs.length; i++) {
      const nm = getOrCreateNetIdentifier(n.id, i, used, cache, `${title(n.id)}_${sp.outs[i]}`);
      if (!driven.has(nm) && !inPorts.includes(nm)) {
        lines.push(`  wire ${nm};`);
        driven.add(nm);
      }
    }
  }
  // For counter regs: declare reg
  for (const n of nodes) {
    if (n.type === "COUNTER") {
      const bits = Math.min(8, Math.max(2, n.bits ?? 4));
      const qn = [...Array(bits)].map((_, i) => getOrCreateNetIdentifier(n.id, i, used, cache, `${title(n.id)}_${specOf(n, defs).outs[i]}`));
      // the internal reg name is separate from output wires
      const regName = generateUniqueName(title(n.id) + "_reg", used);
      // store mapping for later emits: we embed reg name in cache for counter outputs? Not needed.
      // Add manual reg line now, and keep mapping via out net names already declared as wires above.
      // The reg declaration needs to be after wire declarations.
      // We'll push it here and treat out wires already declared.
      lines.push(`  reg [${bits - 1}:0] ${regName};`);
      // Save reg name for per-node use: store in cache under special key
      cache.set(`creg:${n.id}`, regName);
      // Remove regName from driven? It's a reg, not wire.
      void qn;
    }
  }
  lines.push("");

  const srcOf = (node: string, port: number) => {
    const w = wires.find((x) => x.to.node === node && x.to.port === port);
    if (!w) return "1'bx";
    return getOrCreateNetIdentifier(w.from.node, w.from.port, used, cache, title(w.from.node));
  };

  for (const n of nodes) {
    const sp = specOf(n, defs);
    const y = (i = 0) => getOrCreateNetIdentifier(n.id, i, used, cache, `${title(n.id)}_${sp.outs[i] ?? "Y"}`);
    const a = (i: number) => srcOf(n.id, i);
    // Annotate each node's IR for fallback parsers that don't use JSON block
    lines.push(`  // @node ${n.id} type=${n.type} x=${n.x} y=${n.y} ${n.label ? `label=${JSON.stringify(n.label)}` : ""} ${n.bits ? `bits=${n.bits}` : ""} ${n.period ? `period=${n.period}` : ""} ${n.delay != null ? `delay=${n.delay}` : ""}`);
    if (n.type === "INPUT" || n.type === "CLOCK") continue;
    if (n.type === "VCC") { lines.push(`  assign ${y()} = 1'b1;`); continue; }
    if (n.type === "GND") { lines.push(`  assign ${y()} = 1'b0;`); continue; }
    if (n.type === "OUTPUT" || n.type === "LED") {
      const p = cache.get(`probe:${n.id}`);
      if (p) lines.push(`  assign ${p} = ${a(0)};`);
      continue;
    }
    if (isGate(n.type) || n.type === "DELAY") {
      const ins = sp.ins.map((_, i) => a(i));
      const expr =
        n.type === "AND" || n.type === "NAND" ? ins.join(" & ") :
        n.type === "OR" || n.type === "NOR" ? ins.join(" | ") :
        n.type === "XOR" || n.type === "XNOR" ? ins.join(" ^ ") :
        ins[0] ?? "1'bx";
      const wrap = n.type === "NAND" || n.type === "NOR" || n.type === "XNOR" || n.type === "NOT" ? `~(${expr})` : expr;
      lines.push(`  assign ${y()} = ${wrap};`);
      continue;
    }
    if (n.type === "TRI") { lines.push(`  assign ${y()} = ${a(1)} ? ${a(0)} : 1'bz;`); continue; }
    if (n.type === "BUS") { lines.push(`  assign ${y()} = ${sp.ins.map((_, i) => a(i)).join(" | ")};`); continue; }
    if (n.type === "PULLUP") { lines.push(`  assign ${y()} = ${a(0)};`); continue; }
    if (n.type === "PULLDOWN") { lines.push(`  assign ${y()} = ${a(0)};`); continue; }
    if (n.type === "MUX2") { lines.push(`  assign ${y()} = ${a(2)} ? ${a(1)} : ${a(0)};`); continue; }
    if (n.type === "MUX4") {
      lines.push(`  assign ${y()} = ({${a(5)},${a(4)}} == 2'b00) ? ${a(0)} : ({${a(5)},${a(4)}} == 2'b01) ? ${a(1)} : ({${a(5)},${a(4)}} == 2'b10) ? ${a(2)} : ${a(3)};`);
      continue;
    }
    if (n.type === "DEC2") {
      for (let i = 0; i < 4; i++) {
        const aa = i & 1 ? a(0) : `~${a(0)}`;
        const bb = i & 2 ? a(1) : `~${a(1)}`;
        lines.push(`  assign ${y(i)} = ${aa} & ${bb};`);
      }
      continue;
    }
    if (n.type === "ADDER") {
      lines.push(`  assign ${y(0)} = ${a(0)} ^ ${a(1)} ^ ${a(2)};`);
      lines.push(`  assign ${y(1)} = (${a(0)} & ${a(1)}) | (${a(2)} & (${a(0)} ^ ${a(1)}));`);
      continue;
    }
    if (n.type === "DFF") {
      const qReg = y(0);
      lines.push(`  always @(posedge ${a(1)} or posedge ${a(2)}) begin`);
      lines.push(`    if (${a(2)}) ${qReg} <= 1'b0; else ${qReg} <= ${a(0)};`);
      lines.push(`  end`);
      lines.push(`  assign ${y(1)} = ~${qReg};`);
      continue;
    }
    if (n.type === "TFF") {
      const qReg = y(0);
      lines.push(`  always @(posedge ${a(1)} or posedge ${a(2)}) begin`);
      lines.push(`    if (${a(2)}) ${qReg} <= 1'b0; else if (${a(0)}) ${qReg} <= ~${qReg};`);
      lines.push(`  end`);
      lines.push(`  assign ${y(1)} = ~${qReg};`);
      continue;
    }
    if (n.type === "JKFF") {
      const qReg = y(0);
      lines.push(`  always @(posedge ${a(2)} or posedge ${a(3)}) begin`);
      lines.push(`    if (${a(3)}) ${qReg} <= 1'b0;`);
      lines.push(`    else case ({${a(0)}, ${a(1)}})`);
      lines.push(`      2'b10: ${qReg} <= 1'b1; 2'b01: ${qReg} <= 1'b0; 2'b11: ${qReg} <= ~${qReg};`);
      lines.push(`    endcase`);
      lines.push(`  end`);
      lines.push(`  assign ${y(1)} = ~${qReg};`);
      continue;
    }
    if (n.type === "DLATCH") {
      const qReg = y(0);
      lines.push(`  always @(*) if (${a(1)}) ${qReg} = ${a(0)};`);
      lines.push(`  assign ${y(1)} = ~${qReg};`);
      continue;
    }
    if (n.type === "COUNTER") {
      const bits = Math.min(8, Math.max(2, n.bits ?? 4));
      const qn = cache.get(`creg:${n.id}`) ?? generateUniqueName(title(n.id) + "_reg", used);
      // Register was declared earlier; now the sequential logic
      lines.push(`  always @(posedge ${a(0)} or posedge ${a(1)}) begin`);
      lines.push(`    if (${a(1)}) ${qn} <= ${bits}'d0; else ${qn} <= ${qn} + 1'b1;`);
      lines.push(`  end`);
      for (let i = 0; i < bits; i++) lines.push(`  assign ${y(i)} = ${qn}[${i}];`);
      continue;
    }
    if (n.type === "CUSTOM") lines.push(`  // hierarchical ${title(n.id)} ${n.defId ?? ""}`);
  }

  if (nodes.some((n) => isSequential(n.type))) {
    lines.splice(4, 0, "  // Sequential Q ports are driven from always blocks.");
  }

  lines.push("");
  lines.push("endmodule");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Emit VHDL (Circuit IR -> HDL)
// Generates a synthesizable VHDL entity+architecture and embeds IR block.
// ---------------------------------------------------------------------------

export function generateVhdl(doc: Doc): string {
  const mod = sanitizeIdentifier(doc.name || "LogicForge");
  const ins = doc.nodes.filter((n) => n.type === "INPUT" || n.type === "CLOCK");
  const outs = doc.nodes.filter((n) => n.type === "OUTPUT" || n.type === "LED");
  const ports = [
    ...ins.map((n) => `    ${sanitizeIdentifier(nodeTitle(n, doc.defs))} : in  std_logic`),
    ...outs.map((n) => `    ${sanitizeIdentifier(nodeTitle(n, doc.defs))} : out std_logic`),
  ].join(";\n");

  // Build internal signals for VHDL: mirrors Verilog netIds but as std_logic signals
  // We'll reuse Verilog generation for signal list mapping, but translate to VHDL assignments.
  const v = generateVerilog(doc);
  // For a proper VHDL architecture, translate Verilog assigns to VHDL concurrent assignments.
  // To keep it parseable, we also generate a readable VHDL architecture based on the doc.
  const used = new Set<string>(["entity", "architecture", "signal", "process", "begin", "end", "if", "else", "elsif", "case", "when"]);
  const cache = new Map<string, string>();
  const title = (nId: string) => {
    const n = doc.nodes.find((x) => x.id === nId);
    return n ? nodeTitle(n, doc.defs) : nId;
  };
  for (const n of doc.nodes) {
    const sp = specOf(n, doc.defs);
    sp.outs.forEach((nm, i) => {
      const k = `${n.id}:${i}`;
      if (!cache.has(k)) {
        const sig = sanitizeIdentifier(`${title(n.id)}_${nm}`);
        let base = sig, c = 2;
        while (used.has(base)) base = `${sig}_${c++}`;
        used.add(base);
        cache.set(k, base);
      }
    });
    if (n.type === "INPUT" || n.type === "CLOCK") {
      const k = `${n.id}:0`;
      if (!cache.has(k)) {
        const sig = sanitizeIdentifier(title(n.id));
        let base = sig, c = 2;
        while (used.has(base)) base = `${sig}_${c++}`;
        used.add(base);
        cache.set(k, base);
      }
    }
  }
  const probeMap = new Map<string, string>();
  for (const n of outs) {
    const sig = sanitizeIdentifier(title(n.id) + "_o");
    let base = sig, c = 2;
    while (used.has(base)) base = `${sig}_${c++}`;
    used.add(base);
    probeMap.set(n.id, base);
  }
  const sigId = (nodeId: string, port: number) => cache.get(`${nodeId}:${port}`) ?? sanitizeIdentifier(nodeId);
  const srcOf = (nodeId: string, port: number) => {
    const w = doc.wires.find((x) => x.to.node === nodeId && x.to.port === port);
    if (!w) return "'X'";
    return sigId(w.from.node, w.from.port);
  };

  const vsigs: string[] = [];
  const seenSig = new Set<string>();
  for (const n of doc.nodes) {
    const sp = specOf(n, doc.defs);
    for (let i = 0; i < sp.outs.length; i++) {
      const s = sigId(n.id, i);
      if (!ins.some((x) => sigId(x.id, 0) === s) && !outs.some((x) => probeMap.get(x.id) === s) && !seenSig.has(s)) {
        vsigs.push(`  signal ${s} : std_logic;`);
        seenSig.add(s);
      }
    }
  }
  // Counter regs as vectors
  const vregs: string[] = [];
  for (const n of doc.nodes.filter((x) => x.type === "COUNTER")) {
    const bits = Math.min(8, Math.max(2, n.bits ?? 4));
    const reg = sanitizeIdentifier(title(n.id) + "_reg");
    if (!seenSig.has(reg)) {
      vregs.push(`  signal ${reg} : std_logic_vector(${bits - 1} downto 0);`);
      seenSig.add(reg);
    }
  }

  const lines: string[] = [];
  // IR block for VHDL too (using -- comments)
  try {
    const ir = JSON.stringify(doc);
    lines.push(`-- LOGICFORGE_BEGIN`);
    lines.push(`-- ${ir}`);
    lines.push(`-- LOGICFORGE_END`);
  } catch { /* ignore */ }
  lines.push(`-- Generated by LogicForge`);
  lines.push(`library ieee;`);
  lines.push(`use ieee.std_logic_1164.all;`);
  lines.push(`use ieee.numeric_std.all;`);
  lines.push(``);
  lines.push(`entity ${mod} is`);
  lines.push(`  port (`);
  lines.push(ports || `    -- no ports`);
  lines.push(`  );`);
  lines.push(`end entity;`);
  lines.push(``);
  lines.push(`architecture rtl of ${mod} is`);
  vsigs.forEach((s) => lines.push(s));
  vregs.forEach((s) => lines.push(s));
  lines.push(`begin`);

  for (const n of doc.nodes) {
    const sp = specOf(n, doc.defs);
    const y = (i = 0) => sigId(n.id, i);
    const a = (i: number) => srcOf(n.id, i);
    if (n.type === "INPUT" || n.type === "CLOCK") continue;
    if (n.type === "VCC") { lines.push(`  ${y()} <= '1';`); continue; }
    if (n.type === "GND") { lines.push(`  ${y()} <= '0';`); continue; }
    if (n.type === "OUTPUT" || n.type === "LED") {
      const p = probeMap.get(n.id);
      if (p) lines.push(`  ${p} <= ${a(0)};`);
      continue;
    }
    if (n.type === "AND" || n.type === "OR" || n.type === "XOR") {
      const op = n.type === "AND" ? " and " : n.type === "OR" ? " or " : " xor ";
      const ins = sp.ins.map((_, i) => a(i));
      lines.push(`  ${y()} <= ${ins.join(op)};`);
      continue;
    }
    if (n.type === "NAND" || n.type === "NOR" || n.type === "XNOR" || n.type === "NOT") {
      const baseOp = n.type === "NAND" ? " and " : n.type === "NOR" ? " or " : n.type === "XNOR" ? " xnor " : "";
      if (n.type === "NOT") {
        lines.push(`  ${y()} <= not ${a(0)};`);
      } else {
        const ins = sp.ins.map((_, i) => a(i));
        const inner = ins.join(baseOp === " xnor " ? " xor " : baseOp);
        const wrap = n.type === "XNOR" ? `not (${inner})` : `not (${inner})`;
        // For NAND/NOR, VHDL has nand/nor operators directly
        const op2 = n.type === "NAND" ? " nand " : n.type === "NOR" ? " nor " : " xnor ";
        // Prefer direct
        lines.push(`  ${y()} <= ${ins.join(op2)};`);
        void wrap;
      }
      continue;
    }
    if (n.type === "BUFFER" || n.type === "DELAY") { lines.push(`  ${y()} <= ${a(0)};`); continue; }
    if (n.type === "TRI") { lines.push(`  ${y()} <= ${a(0)} when ${a(1)} = '1' else 'Z';`); continue; }
    if (n.type === "BUS") { lines.push(`  ${y()} <= ${sp.ins.map((_, i) => a(i)).join(" or ")};`); continue; }
    if (n.type === "PULLUP" || n.type === "PULLDOWN") { lines.push(`  ${y()} <= ${a(0)};`); continue; }
    if (n.type === "MUX2") { lines.push(`  ${y()} <= ${a(1)} when ${a(2)} = '1' else ${a(0)};`); continue; }
    if (n.type === "MUX4") {
      lines.push(`  with ${a(4)} & ${a(5)} select`);
      lines.push(`    ${y()} <= ${a(0)} when "00",`);
      lines.push(`             ${a(1)} when "01",`);
      lines.push(`             ${a(2)} when "10",`);
      lines.push(`             ${a(3)} when others;`);
      continue;
    }
    if (n.type === "DEC2") {
      for (let i = 0; i < 4; i++) {
        const aa = i & 1 ? a(0) : `not ${a(0)}`;
        const bb = i & 2 ? a(1) : `not ${a(1)}`;
        lines.push(`  ${y(i)} <= ${aa} and ${bb};`);
      }
      continue;
    }
    if (n.type === "ADDER") {
      lines.push(`  ${y(0)} <= ${a(0)} xor ${a(1)} xor ${a(2)};`);
      lines.push(`  ${y(1)} <= (${a(0)} and ${a(1)}) or (${a(2)} and (${a(0)} xor ${a(1)}));`);
      continue;
    }
    if (n.type === "DFF") {
      const q = y(0);
      lines.push(`  process(${a(1)}, ${a(2)})`);
      lines.push(`  begin`);
      lines.push(`    if ${a(2)} = '1' then`);
      lines.push(`      ${q} <= '0';`);
      lines.push(`    elsif rising_edge(${a(1)}) then`);
      lines.push(`      ${q} <= ${a(0)};`);
      lines.push(`    end if;`);
      lines.push(`  end process;`);
      lines.push(`  ${y(1)} <= not ${q};`);
      continue;
    }
    if (n.type === "TFF") {
      const q = y(0);
      lines.push(`  process(${a(1)}, ${a(2)})`);
      lines.push(`  begin`);
      lines.push(`    if ${a(2)} = '1' then`);
      lines.push(`      ${q} <= '0';`);
      lines.push(`    elsif rising_edge(${a(1)}) then`);
      lines.push(`      if ${a(0)} = '1' then ${q} <= not ${q}; end if;`);
      lines.push(`    end if;`);
      lines.push(`  end process;`);
      lines.push(`  ${y(1)} <= not ${q};`);
      continue;
    }
    if (n.type === "JKFF") {
      const q = y(0);
      lines.push(`  process(${a(2)}, ${a(3)})`);
      lines.push(`  begin`);
      lines.push(`    if ${a(3)} = '1' then`);
      lines.push(`      ${q} <= '0';`);
      lines.push(`    elsif rising_edge(${a(2)}) then`);
      lines.push(`      case ${a(0)} & ${a(1)} is`);
      lines.push(`        when "10" => ${q} <= '1';`);
      lines.push(`        when "01" => ${q} <= '0';`);
      lines.push(`        when "11" => ${q} <= not ${q};`);
      lines.push(`        when others => null;`);
      lines.push(`      end case;`);
      lines.push(`    end if;`);
      lines.push(`  end process;`);
      lines.push(`  ${y(1)} <= not ${q};`);
      continue;
    }
    if (n.type === "DLATCH") {
      const q = y(0);
      lines.push(`  process(${a(1)}, ${a(0)})`);
      lines.push(`  begin`);
      lines.push(`    if ${a(1)} = '1' then ${q} <= ${a(0)}; end if;`);
      lines.push(`  end process;`);
      lines.push(`  ${y(1)} <= not ${q};`);
      continue;
    }
    if (n.type === "COUNTER") {
      const bits = Math.min(8, Math.max(2, n.bits ?? 4));
      const reg = sanitizeIdentifier(title(n.id) + "_reg");
      lines.push(`  process(${a(0)}, ${a(1)})`);
      lines.push(`  begin`);
      lines.push(`    if ${a(1)} = '1' then`);
      lines.push(`      ${reg} <= (others => '0');`);
      lines.push(`    elsif rising_edge(${a(0)}) then`);
      lines.push(`      ${reg} <= std_logic_vector(unsigned(${reg}) + 1);`);
      lines.push(`    end if;`);
      lines.push(`  end process;`);
      for (let i = 0; i < bits; i++) lines.push(`  ${y(i)} <= ${reg}(${i});`);
      continue;
    }
    if (n.type === "CUSTOM") lines.push(`  -- hierarchical ${title(n.id)}`);
  }

  lines.push(`end architecture;`);
  lines.push(``);
  // Append Verilog companion as comment for cross-check (our VHDL parser can also extract it)
  lines.push(`-- ===== Verilog companion =====`);
  v.split("\n").forEach((l) => lines.push(`-- ${l}`));
  lines.push(``);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Parse helpers: IR extraction, comment stripping, etc.
// ---------------------------------------------------------------------------

function tryExtractIR(source: string): Doc | null {
  const beginIdx = source.indexOf("LOGICFORGE_BEGIN");
  const endIdx = source.indexOf("LOGICFORGE_END");
  if (beginIdx === -1 || endIdx === -1 || endIdx <= beginIdx) return null;
  const block = source.slice(beginIdx, endIdx);
  // Split into lines, strip comment prefixes (-- or //)
  const lines = block.split("\n");
  const jsonLines = lines.map((l) => {
    const m = l.match(/^\s*(?:\/\/|--)\s?(.*)$/);
    if (m) return m[1];
    // Also handle line with LOGICFORGE_BEGIN itself
    const m2 = l.match(/LOGICFORGE_BEGIN\s*(.*)/);
    if (m2) return m2[1];
    return l;
  });
  const joined = jsonLines.join("\n");
  const s = joined.indexOf("{");
  const e = joined.lastIndexOf("}");
  if (s === -1 || e === -1 || e <= s) return null;
  const jsonStr = joined.slice(s, e + 1);
  try {
    const doc = JSON.parse(jsonStr);
    if (doc && Array.isArray(doc.nodes) && Array.isArray(doc.wires)) {
      if (!Array.isArray(doc.defs)) doc.defs = [];
      return doc as Doc;
    }
  } catch {
    return null;
  }
  return null;
}

function stripVerilogComments(s: string): string {
  // Remove /* */ first
  let out = s.replace(/\/\*[\s\S]*?\*\//g, "");
  // Remove // lines but keep IR block? IR already extracted, so we can strip all //.
  out = out.replace(/\/\/.*$/gm, "");
  return out;
}

function stripVhdlComments(s: string): string {
  // VHDL comments are -- till end of line
  // But need to keep IR? IR already extracted.
  return s.replace(/--.*$/gm, "");
}

// ---------------------------------------------------------------------------
// Parse result types
// ---------------------------------------------------------------------------

export interface ParseResult {
  doc: Doc;
  errors: string[];
  warnings: string[];
}

// ---------------------------------------------------------------------------
// Verilog -> Circuit IR parser
// ---------------------------------------------------------------------------

export function parseVerilogHdl(source: string): ParseResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  if (!source || !source.trim()) {
    return { doc: { nodes: [], wires: [], defs: [], name: "Untitled" }, errors: ["Empty source"], warnings };
  }

  const irDoc = tryExtractIR(source);
  if (irDoc) {
    // Return IR directly for lossless round-trip
    // Ensure defs
    if (!irDoc.defs) irDoc.defs = [];
    return { doc: irDoc, errors, warnings };
  }

  const cleaned = stripVerilogComments(source);

  // Extract module
  const modRe = /module\s+(\w+)\s*\(([^)]*)\)\s*;/is;
  const modMatch = cleaned.match(modRe);
  let modName = "Imported";
  let headerPorts = "";
  if (modMatch) {
    modName = modMatch[1];
    headerPorts = modMatch[2];
  } else {
    warnings.push("No module header found, attempting generic parse");
  }

  // Body: between first ';' after module and endmodule
  let body = "";
  const bodyRe = /module\s+\w+\s*\([^)]*\)\s*;([\s\S]*?)endmodule\s*/i;
  const bodyMatch = cleaned.match(bodyRe);
  if (bodyMatch) body = bodyMatch[1];
  else {
    // No endmodule, take everything after module header
    const idx = cleaned.indexOf(";");
    if (idx !== -1) body = cleaned.slice(idx + 1);
    else body = cleaned;
    warnings.push("No endmodule found, using full file as body");
  }

  const inputNets = new Set<string>();
  const outputNets = new Set<string>();
  const wireNets = new Set<string>();
  const regMap = new Map<string, number>();

  // Header ports
  if (headerPorts) {
    const parts = headerPorts.split(",").map((s) => s.trim()).filter(Boolean);
    for (const part of parts) {
      const m = part.match(/^(input|output)\s+(?:wire|reg)?\s*(?:\[[^\]]+\]\s*)?(\w+)$/i);
      if (m) {
        if (m[1].toLowerCase() === "input") inputNets.add(m[2]);
        else outputNets.add(m[2]);
      } else {
        const bare = part.match(/^(\w+)$/);
        if (bare) {
          // Direction unknown, will be resolved via body declarations
          // Mark as potential io, but not add yet
        }
      }
    }
  }

  // Body declarations: input/output/wire/reg with possible vector and list
  function collectDecls(keyword: string) {
    // Pattern: keyword [range] list ;
    const re = new RegExp("\\b" + keyword + "\\b\\s*(\\[[^\\]]+\\]\\s*)?([^;]+);", "gi");
    let m: RegExpExecArray | null;
    while ((m = re.exec(body)) !== null) {
      const range = m[1] ?? "";
      const listStr = m[2];
      let bits = 1;
      const w = range.match(/\[\s*(\d+)\s*:\s*0\s*\]/);
      if (w) bits = parseInt(w[1], 10) + 1;
      const entries = listStr.split(",");
      for (const entry of entries) {
        const trimmed = entry.trim();
        if (!trimmed) continue;
        // Remove assignment part e.g., "a = 1'b0"
        const lhs = trimmed.split("=")[0].trim();
        // Extract identifier (allow vector) before any [
        const idMatch = lhs.match(/^(\w+)/);
        if (!idMatch) continue;
        const name = idMatch[1];
        if (keyword === "reg") {
          regMap.set(name, bits);
        } else if (keyword === "input") inputNets.add(name);
        else if (keyword === "output") outputNets.add(name);
        else if (keyword === "wire") wireNets.add(name);
      }
    }
  }
  collectDecls("input");
  collectDecls("output");
  collectDecls("wire");
  collectDecls("reg");

  // Also handle cases where header used bare identifiers and body declares them as input/output via "input A,B;" style already captured.
  // If still no inputs/outputs but body has them, fine.

  // Collect assigns
  const assigns: { lhs: string; rhs: string; raw: string }[] = [];
  const assignRe = /assign\s+(\w+)(?:\s*\[[^\]]+\])?\s*=\s*([^;]+);/gi;
  let m: RegExpExecArray | null;
  while ((m = assignRe.exec(body)) !== null) {
    assigns.push({ lhs: m[1].trim(), rhs: m[2].trim(), raw: m[0] });
  }

  // Collect always blocks
  const alwaysBlocks: { header: string; body: string; raw: string }[] = [];
  const alwaysRe = /always\s*@\s*\(([^)]+)\)\s*begin([\s\S]*?)end/gi;
  while ((m = alwaysRe.exec(body)) !== null) {
    alwaysBlocks.push({ header: m[1].trim(), body: m[2].trim(), raw: m[0] });
  }
  // Latch without begin/end: always @(*) if (EN) Q = D;
  const latchRe = /always\s*@\s*\(\s*\*\s*\)\s*if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*=\s*(\w+)\s*;/gi;
  while ((m = latchRe.exec(body)) !== null) {
    // Avoid duplicating those already captured via begin/end with @(*)
    const whole = m[0];
    if (!alwaysBlocks.some((b) => b.raw.includes(whole))) {
      alwaysBlocks.push({ header: "*", body: `if (${m[1]}) ${m[2]} = ${m[3]};`, raw: whole });
    }
  }

  // Data structures for reconstruction
  const nodes: CNode[] = [];
  const nodeInputs = new Map<string, string[]>();
  const netDriver = new Map<string, { nodeId: string; port: number }>();
  const consumedAssigns = new Set<number>();
  const consumedAlways = new Set<number>();

  function addNode(node: CNode) {
    nodes.push(node);
  }
  function registerDriver(net: string, nodeId: string, port: number) {
    netDriver.set(net, { nodeId, port });
  }

  // Step 1: INPUT / CLOCK nodes — initially create all as INPUT/CLOCK heuristically,
  // but avoid misclassifying async resets as clocks: only the first posedge in a block is the clock.
  for (const net of inputNets) {
    const firstClocks = new Set<string>();
    for (const b of alwaysBlocks) {
      const first = [...b.header.matchAll(/posedge\s+(\w+)/g)].map((x) => x[1])[0];
      if (first) firstClocks.add(first);
    }
    const isClock = /clk/i.test(net) || firstClocks.has(net);
    const type: NodeKind = isClock ? "CLOCK" : "INPUT";
    const id = generateUniqueId(type === "CLOCK" ? "clk_" : "in_");
    const node: CNode = {
      id,
      type,
      x: 0,
      y: 0,
      rot: 0,
      inputs: 0,
      label: net,
      ...(type === "INPUT" ? { value: 0 as const } : { period: 12, domain: "clk" }),
      delay: (CATALOG as any)[type]?.defaultDelay ?? 0,
    };
    addNode(node);
    registerDriver(net, id, 0);
  }

  // Helper to get or create const driver
  function getConstDriver(val: "0" | "1"): { nodeId: string; port: number } {
    const key = val === "1" ? "__VCC__" : "__GND__";
    const hit = netDriver.get(key);
    if (hit) return hit;
    const type: NodeKind = val === "1" ? "VCC" : "GND";
    const id = generateUniqueId(val === "1" ? "vcc_" : "gnd_");
    const node: CNode = { id, type, x: 0, y: 0, rot: 0, inputs: 0, delay: 0 };
    addNode(node);
    registerDriver(key, id, 0);
    return { nodeId: id, port: 0 };
  }

  // Step 2: Sequential nodes from always blocks
  // Try COUNTER first
  for (const [regName, bits] of [...regMap.entries()]) {
    const idx = alwaysBlocks.findIndex((b, i) => !consumedAlways.has(i) && b.body.includes(regName) && b.header.includes("posedge"));
    if (idx === -1) continue;
    const block = alwaysBlocks[idx];
    // Check for counter pattern: contains reg <= and + 1
    if (!block.body.includes(`${regName} <=`) || !block.body.includes(`${regName} +`)) continue;
    const posEdges = [...block.header.matchAll(/posedge\s+(\w+)/g)].map((x) => x[1]);
    const clkNet = posEdges[0];
    const rstNet = posEdges[1] ?? null;
    if (!clkNet) continue;
    // Find output assigns for this counter
    const pairs: { idx: number; lhs: string; bit: number }[] = [];
    for (let ai = 0; ai < assigns.length; ai++) {
      if (consumedAssigns.has(ai)) continue;
      const a = assigns[ai];
      const mm = a.rhs.match(new RegExp(`^\\s*${regName}\\s*\\[\\s*(\\d+)\\s*\\]\\s*$`));
      if (mm) pairs.push({ idx: ai, lhs: a.lhs, bit: parseInt(mm[1], 10) });
    }
    if (!pairs.length) continue;
    pairs.sort((a, b) => a.bit - b.bit);
    const maxBit = Math.max(...pairs.map((p) => p.bit));
    const finalBits = Math.min(8, Math.max(bits, maxBit + 1));
    const nodeId = generateUniqueId("ctr_");
    const node: CNode = {
      id: nodeId,
      type: "COUNTER",
      x: 0,
      y: 0,
      rot: 0,
      inputs: 2,
      bits: finalBits,
      label: regName.replace(/_reg$/, ""),
      delay: CATALOG["COUNTER"].defaultDelay,
    };
    addNode(node);
    pairs.forEach((p) => {
      registerDriver(p.lhs, nodeId, p.bit);
      consumedAssigns.add(p.idx);
    });
    // Store inputs for wiring
    nodeInputs.set(nodeId, [clkNet, rstNet ?? ""]);
    consumedAlways.add(idx);
    // Mark reg as consumed so not reused
    regMap.delete(regName);
  }

  // Helper for sequential DFF/TFF/JKFF/DLATCH
  function tryParseSequential(): boolean {
    let progressed = false;
    for (let idx = 0; idx < alwaysBlocks.length; idx++) {
      if (consumedAlways.has(idx)) continue;
      const block = alwaysBlocks[idx];
      const header = block.header;
      const body = block.body;

      // DLATCH: always @(*) if (EN) Q = D;
      if (header === "*" && body.match(/if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*=\s*(\w+)\s*;/)) {
        const m2 = body.match(/if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*=\s*(\w+)\s*;/);
        if (!m2) continue;
        const en = m2[1], q = m2[2], d = m2[3];
        const nodeId = generateUniqueId("lat_");
        const node: CNode = { id: nodeId, type: "DLATCH", x: 0, y: 0, rot: 0, inputs: 2, delay: CATALOG["DLATCH"].defaultDelay, label: q };
        addNode(node);
        registerDriver(q, nodeId, 0);
        // Find Qn assign
        const qnIdx = assigns.findIndex((a, i) => !consumedAssigns.has(i) && a.rhs.replace(/\s/g, "") === `~${q}`);
        if (qnIdx !== -1) {
          registerDriver(assigns[qnIdx].lhs, nodeId, 1);
          consumedAssigns.add(qnIdx);
        }
        nodeInputs.set(nodeId, [d, en]);
        consumedAlways.add(idx);
        progressed = true;
        continue;
      }

      // For posedge blocks (DFF, TFF, JKFF)
      if (!header.includes("posedge")) continue;
      const posEdges = [...header.matchAll(/posedge\s+(\w+)/g)].map((x) => x[1]);
      const clkNet = posEdges[0];
      const rstNet = posEdges[1] ?? null;

      // JKFF has case
      if (body.includes("case") && body.includes("2'b10")) {
        // JKFF
        const rstMatch = body.match(/if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*<=\s*1'b0\s*;/);
        const caseMatch = body.match(/case\s*\(\s*\{\s*(\w+)\s*,\s*(\w+)\s*\}\s*\)/);
        // Find Q name: from rstMatch second group
        if (!rstMatch || !caseMatch) continue;
        const rstCond = rstMatch[1];
        const q = rstMatch[2];
        const j = caseMatch[1], k = caseMatch[2];
        // Check q matches later: find the target of 2'b10 lines
        // We assume q is same throughout
        const nodeId = generateUniqueId("jk_");
        const node: CNode = { id: nodeId, type: "JKFF", x: 0, y: 0, rot: 0, inputs: 4, delay: CATALOG["JKFF"].defaultDelay, label: q };
        addNode(node);
        registerDriver(q, nodeId, 0);
        const qnIdx = assigns.findIndex((a, i) => !consumedAssigns.has(i) && a.rhs.replace(/\s/g, "") === `~${q}`);
        if (qnIdx !== -1) {
          registerDriver(assigns[qnIdx].lhs, nodeId, 1);
          consumedAssigns.add(qnIdx);
        }
        nodeInputs.set(nodeId, [j, k, clkNet, rstNet ?? rstCond]);
        consumedAlways.add(idx);
        progressed = true;
        continue;
      }

      // TFF: contains else if (T)
      if (body.includes("else if") && body.match(/else\s*if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*<=\s*~\s*(\w+)\s*;/)) {
        const m2 = body.match(/if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*<=\s*1'b0\s*;\s*else\s*if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*<=\s*~\s*(\w+)\s*;/s);
        if (!m2) continue;
        const rstCond = m2[1], q1 = m2[2], t = m2[3], q2 = m2[4], q3 = m2[5];
        if (q1 !== q2 || q1 !== q3) continue;
        const q = q1;
        const nodeId = generateUniqueId("tff_");
        const node: CNode = { id: nodeId, type: "TFF", x: 0, y: 0, rot: 0, inputs: 3, delay: CATALOG["TFF"].defaultDelay, label: q };
        addNode(node);
        registerDriver(q, nodeId, 0);
        const qnIdx = assigns.findIndex((a, i) => !consumedAssigns.has(i) && a.rhs.replace(/\s/g, "") === `~${q}`);
        if (qnIdx !== -1) {
          registerDriver(assigns[qnIdx].lhs, nodeId, 1);
          consumedAssigns.add(qnIdx);
        }
        nodeInputs.set(nodeId, [t, clkNet, rstNet ?? rstCond]);
        consumedAlways.add(idx);
        progressed = true;
        continue;
      }

      // DFF: if (RST) Q <= 1'b0; else Q <= D;
      const dffM = body.match(/if\s*\(\s*(\w+)\s*\)\s*(\w+)\s*<=\s*1'b0\s*;\s*else\s*(\w+)\s*<=\s*(\w+)\s*;/s);
      if (dffM) {
        const rstCond = dffM[1], q1 = dffM[2], q2 = dffM[3], d = dffM[4];
        if (q1 !== q2) continue;
        const q = q1;
        const nodeId = generateUniqueId("dff_");
        const node: CNode = { id: nodeId, type: "DFF", x: 0, y: 0, rot: 0, inputs: 3, delay: CATALOG["DFF"].defaultDelay, label: q };
        addNode(node);
        registerDriver(q, nodeId, 0);
        const qnIdx = assigns.findIndex((a, i) => !consumedAssigns.has(i) && a.rhs.replace(/\s/g, "") === `~${q}`);
        if (qnIdx !== -1) {
          registerDriver(assigns[qnIdx].lhs, nodeId, 1);
          consumedAssigns.add(qnIdx);
        }
        nodeInputs.set(nodeId, [d, clkNet, rstNet ?? rstCond]);
        consumedAlways.add(idx);
        progressed = true;
        continue;
      }

      // Simple DFF without reset: Q <= D;
      const simpleM = body.match(/(\w+)\s*<=\s*(\w+)\s*;/);
      if (simpleM && !body.includes("if")) {
        const q = simpleM[1], d = simpleM[2];
        const nodeId = generateUniqueId("dff_");
        const node: CNode = { id: nodeId, type: "DFF", x: 0, y: 0, rot: 0, inputs: 3, delay: CATALOG["DFF"].defaultDelay, label: q };
        addNode(node);
        registerDriver(q, nodeId, 0);
        const qnIdx = assigns.findIndex((a, i) => !consumedAssigns.has(i) && a.rhs.replace(/\s/g, "") === `~${q}`);
        if (qnIdx !== -1) {
          registerDriver(assigns[qnIdx].lhs, nodeId, 1);
          consumedAssigns.add(qnIdx);
        }
        nodeInputs.set(nodeId, [d, clkNet, ""]);
        consumedAlways.add(idx);
        progressed = true;
        continue;
      }
    }
    return progressed;
  }
  // Try sequentially until no progress
  while (tryParseSequential()) { /* loop */ }

  // Step 3: Output alias vs expression detection
  const outputAliasMap = new Map<string, string>();
  const outputExpressionSet = new Set<string>();
  const aliasAssignIndices: number[] = [];
  for (let ai = 0; ai < assigns.length; ai++) {
    if (consumedAssigns.has(ai)) continue;
    const a = assigns[ai];
    if (!outputNets.has(a.lhs)) continue;
    const t = a.rhs.trim();
    if (/^\w+$/.test(t)) {
      outputAliasMap.set(a.lhs, t);
      aliasAssignIndices.push(ai);
    } else {
      outputExpressionSet.add(a.lhs);
      // leave for gate inference
    }
  }
  for (const idx of aliasAssignIndices) consumedAssigns.add(idx);

  // Helper: infer gate from RHS
  function inferGate(rhs: string): { type: NodeKind; inputs: number; inputNets: string[] } | null {
    const t = rhs.trim();
    if (t === "1'b1") return { type: "VCC", inputs: 0, inputNets: [] };
    if (t === "1'b0") return { type: "GND", inputs: 0, inputNets: [] };
    if (t === "1'bx" || t === "1'bz") return null;
    // TRI: ... ? ... : 1'bz
    if (t.includes("?") && t.includes("1'bz")) {
      const mm = t.match(/(\w+)\s*\?\s*(\w+)\s*:\s*1'bz/);
      if (mm) {
        const sel = mm[1], data = mm[2];
        return { type: "TRI", inputs: 2, inputNets: [data, sel] };
      }
    }
    // MUX handling (before generic operators)
    if (t.includes("?") && t.includes(":")) {
      if (t.includes("2'b00")) {
        const selMatch = t.match(/\{\s*(\w+)\s*,\s*(\w+)\s*\}/);
        if (selMatch) {
          const s1 = selMatch[1], s0 = selMatch[2];
          // Extract branches: split by ? and :
          // The pattern is: ({S1,S0}==2'b00)?I0: ({S1,S0}==2'b01)?I1: ...
          // We'll extract I's by looking for ? I and : I patterns
          const qParts = t.split("?");
          // Simpler: collect all identifiers that appear before ':' as I candidates
          // Use regex for ?\s*(\w+)\s*:
          const branchMatches = [...t.matchAll(/\?\s*(\w+)\s*:/g)].map((x) => x[1]);
          const last = t.match(/:\s*(\w+)\s*$/);
          const branches = [...branchMatches];
          if (last) branches.push(last[1]);
          // Also need to handle the first branch after first ? is I0 etc.
          // Our branches length should be 4 (I0,I1,I2,I3) where the last element is I3
          // But branchMatches captures I0,I1,I2 plus last captures I3
          if (branches.length >= 4) {
            const [i0, i1, i2, i3] = branches;
            return { type: "MUX4", inputs: 6, inputNets: [i0, i1, i2, i3, s0, s1] };
          }
        }
      } else {
        const mm = t.match(/(\w+)\s*\?\s*(\w+)\s*:\s*(\w+)/);
        if (mm) {
          const sel = mm[1], i1 = mm[2], i0 = mm[3];
          return { type: "MUX2", inputs: 3, inputNets: [i0, i1, sel] };
        }
      }
    }

    let neg = false;
    let inner = t;
    const negWrap = t.match(/^\s*~\s*\(\s*(.+)\s*\)\s*$/);
    if (negWrap) {
      neg = true;
      inner = negWrap[1].trim();
    } else if (/^\s*~\s*\w+\s*$/.test(t)) {
      const mm = t.match(/^\s*~\s*(\w+)\s*$/);
      if (mm) return { type: "NOT", inputs: 1, inputNets: [mm[1]] };
    }

    if (neg && /^\w+$/.test(inner)) {
      return { type: "NOT", inputs: 1, inputNets: [inner] };
    }

    // Detect bus/or/and etc
    const hasAnd = inner.includes("&");
    const hasOr = inner.includes("|");
    const hasXor = inner.includes("^");

    // Mixed operators like for adder carry ` (A & B) | (C & (A ^ B))` will have both & | ^ - skip here, will be handled via grouping or fallback
    if (hasAnd && !hasOr && !hasXor) {
      const parts = inner.split("&").map((s) => s.trim()).filter(Boolean);
      const nets = parts.map((p) => {
        const m = p.match(/~?\s*(\w+)/);
        return m ? m[1] : p;
      });
      if (nets.length >= 1) {
        const type: NodeKind = neg ? "NAND" : "AND";
        return { type, inputs: nets.length, inputNets: nets };
      }
    }
    if (hasOr && !hasAnd && !hasXor) {
      // For OR, split by | but need to avoid splitting on trailing |? Use regex
      const parts = inner.split("|").map((s) => s.trim()).filter(Boolean);
      const nets = parts.map((p) => {
        const m = p.match(/~?\s*(\w+)/);
        return m ? m[1] : p;
      });
      if (nets.length >= 1) {
        const type: NodeKind = neg ? "NOR" : "OR";
        return { type, inputs: nets.length, inputNets: nets };
      }
    }
    if (hasXor && !hasAnd && !hasOr) {
      const parts = inner.split("^").map((s) => s.trim()).filter(Boolean);
      const nets = parts.map((p) => {
        const m = p.match(/~?\s*(\w+)/);
        return m ? m[1] : p;
      });
      if (nets.length >= 1) {
        const type: NodeKind = neg ? "XNOR" : "XOR";
        return { type, inputs: nets.length, inputNets: nets };
      }
    }

    if (/^\w+$/.test(inner)) {
      if (neg) return { type: "NOT", inputs: 1, inputNets: [inner] };
      return { type: "BUFFER", inputs: 1, inputNets: [inner] };
    }

    // For complex like `(A & B) | (C & (A ^ B))` fallback: try to detect as adder carry if pattern matches
    // If not, return null to indicate unknown
    return null;
  }

  // Step 4: Grouped components DEC2, ADDER
  // DEC2 grouping — allow both internal wires and output ports (e.g., Y0..Y3 may be module outputs)
  {
    const candidates: { idx: number; lhs: string; rhs: string; base: string[]; negMap: Map<string, boolean> }[] = [];
    for (let ai = 0; ai < assigns.length; ai++) {
      if (consumedAssigns.has(ai)) continue;
      const a = assigns[ai];
      // Do not skip output ports: a DEC2 may directly drive output ports (Y0..Y3)
      const t = a.rhs.trim();
      if (/^\s*~?\w+\s*&\s*~?\w+\s*$/.test(t)) {
        const parts = t.split("&").map((s) => s.trim());
        const nets: string[] = [];
        const negMap = new Map<string, boolean>();
        for (const p of parts) {
          const m = p.match(/^\s*(~)?\s*(\w+)\s*$/);
          if (!m) { nets.length = 0; break; }
          const neg = !!m[1];
          const net = m[2];
          nets.push(net);
          negMap.set(net, neg);
        }
        if (nets.length === 2 && nets[0] !== nets[1]) {
          const base = [...nets].sort();
          candidates.push({ idx: ai, lhs: a.lhs, rhs: t, base, negMap });
        }
      }
    }
    // Group by base join
    const groups = new Map<string, typeof candidates>();
    for (const c of candidates) {
      const key = c.base.join(",");
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key)!.push(c);
    }
    for (const [key, group] of groups) {
      if (group.length !== 4) continue;
      const base = key.split(",");
      // Check coverage of 4 combos
      const seen = new Set<string>();
      let valid = true;
      for (const g of group) {
        // For each base net, get neg flag from negMap, but need to handle part order: g.base sorted, but negMap keyed by net
        const pattern = base.map((net) => (g.negMap.get(net) ? "1" : "0")).join("");
        // But our neg flag encoding inverted? For ~A & ~B -> both neg true -> pattern "11" ?
        // However DEC2 spec: Y0 = ~A & ~B => 00 inverted? Let's treat neg true means original was inverted: In DEC2, ~A corresponds to input low, but for grouping we just need 4 distinct combos.
        seen.add(pattern);
      }
      if (seen.size !== 4) continue;
      // Also need to ensure each pattern appears exactly once (size 4 already ensures)
      // Create DEC2 node
      const a0 = base[0], a1 = base[1]; // sorted order, but original order for DEC2 should be as original spec: inputs are A (port0) and B (port1). Which order? In emit, DEC2 inputs are A (idx0) and B (idx1) in order they were wired. For sorting base, we lose order. But we can attempt to infer order from first candidate's term order? Simpler to use sorted order as generic.
      // Try to map base to actual nets order by appearance across group: prefer alphabetical? Acceptable.
      const nodeId = generateUniqueId("dec_");
      const node: CNode = { id: nodeId, type: "DEC2", x: 0, y: 0, rot: 0, inputs: 2, delay: CATALOG["DEC2"].defaultDelay, label: `DEC_${base.join("")}` };
      addNode(node);
      // Need to map group lhs's to ports 0..3 according to pattern value.
      // Pattern encoding: Let's compute index as binary value where neg false corresponds to 1? For DEC2, Y index = (B?2:0)+(A?1:0) per emit: aa = i &1 ? A : ~A ; bb = i &2 ? B : ~B ; So i=0 => ~A & ~B ; i=1 => A & ~B ; i=2 => ~A & B ; i=3 => A & B
      // So for our pattern where neg true means ~, we have ~A corresponds to bit 0 (since i's bit 0 says A present without ~). So pattern for Y0: negMap[A]=true, negMap[B]=true => corresponds to i=0.
      // So we can compute index as (negMap[A]?0:1) + (negMap[B]?0:2)
      const sortedMap = new Map<number, string>(); // index -> lhs
      for (const g of group) {
        const negA = g.negMap.get(base[0]) ? 0 : 1;
        const negB = g.negMap.get(base[1]) ? 0 : 2;
        const idx = negA + negB;
        sortedMap.set(idx, g.lhs);
      }
      for (let i = 0; i < 4; i++) {
        const lhs = sortedMap.get(i);
        if (!lhs) { valid = false; break; }
        registerDriver(lhs, nodeId, i);
      }
      if (!valid) continue;
      // Remove those assigns
      for (const g of group) consumedAssigns.add(g.idx);
      // Input nets: base[0], base[1] in sorted order. But we lost original order: we should keep sorted order as inputs.
      nodeInputs.set(nodeId, [base[0], base[1]]);
    }
  }

  // ADDER grouping
  {
    const sumCandidates: { idx: number; lhs: string; nets: string[] }[] = [];
    const carryCandidates: { idx: number; lhs: string; nets: string[] }[] = [];
    for (let ai = 0; ai < assigns.length; ai++) {
      if (consumedAssigns.has(ai)) continue;
      const a = assigns[ai];
      const t = a.rhs.trim();
      if (/^\s*\w+\s*\^\s*\w+\s*\^\s*\w+\s*$/.test(t)) {
        const parts = t.split("^").map((s) => s.trim().match(/(\w+)/)?.[1] ?? "");
        if (parts.length === 3 && parts.every(Boolean)) {
          sumCandidates.push({ idx: ai, lhs: a.lhs, nets: parts as string[] });
        }
      } else if (/\(\s*\w+\s*&\s*\w+\s*\)\s*\|\s*\(\s*\w+\s*&\s*\(\s*\w+\s*\^\s*\w+\s*\)\s*\)/.test(t)) {
        const m = t.match(/\(\s*(\w+)\s*&\s*(\w+)\s*\)\s*\|\s*\(\s*(\w+)\s*&\s*\(\s*(\w+)\s*\^\s*(\w+)\s*\)\s*\)/);
        if (m) {
          const nets = [m[1], m[2], m[3]];
          // Validate that inner xor uses same first two nets (m4,m5)
          if (m[4] === m[1] && m[5] === m[2]) {
            carryCandidates.push({ idx: ai, lhs: a.lhs, nets });
          } else {
            // Still consider but with alternativenets
            carryCandidates.push({ idx: ai, lhs: a.lhs, nets });
          }
        }
      }
    }
    // Pair sum and carry with same set
    const usedSum = new Set<number>();
    const usedCarry = new Set<number>();
    for (const s of sumCandidates) {
      if (usedSum.has(s.idx)) continue;
      for (const c of carryCandidates) {
        if (usedCarry.has(c.idx)) continue;
        const setS = new Set(s.nets);
        const setC = new Set(c.nets);
        if (setS.size !== 3 || setC.size !== 3) continue;
        const equal = [...setS].every((x) => setC.has(x));
        if (!equal) continue;
        // Found adder
        const nodeId = generateUniqueId("add_");
        const node: CNode = { id: nodeId, type: "ADDER", x: 0, y: 0, rot: 0, inputs: 3, delay: CATALOG["ADDER"].defaultDelay };
        addNode(node);
        registerDriver(s.lhs, nodeId, 0);
        registerDriver(c.lhs, nodeId, 1);
        // Inputs order is as sum nets order
        nodeInputs.set(nodeId, s.nets);
        consumedAssigns.add(s.idx);
        consumedAssigns.add(c.idx);
        usedSum.add(s.idx);
        usedCarry.add(c.idx);
        break;
      }
    }
  }

  // Step 5: Single gate inference for remaining assigns
  for (let ai = 0; ai < assigns.length; ai++) {
    if (consumedAssigns.has(ai)) continue;
    const a = assigns[ai];
    // Skip if lhs already driven? Could be duplicate assign for same net (should not)
    if (netDriver.has(a.lhs)) {
      warnings.push(`Duplicate driver for net ${a.lhs}, skipping second`);
      continue;
    }
    const inf = inferGate(a.rhs);
    if (!inf) {
      warnings.push(`Could not infer gate for assign ${a.lhs} = ${a.rhs}, treating as buffer`);
      // Fallback to buffer if rhs is single net?
      const m = a.rhs.trim().match(/^(\w+)$/);
      if (m) {
        const nodeId = generateUniqueId("buf_");
        const node: CNode = { id: nodeId, type: "BUFFER", x: 0, y: 0, rot: 0, inputs: 1, delay: CATALOG["BUFFER"].defaultDelay };
        addNode(node);
        registerDriver(a.lhs, nodeId, 0);
        nodeInputs.set(nodeId, [m[1]]);
      } else {
        // Unknown; create buffer with floating input
        const nodeId = generateUniqueId("buf_");
        const node: CNode = { id: nodeId, type: "BUFFER", x: 0, y: 0, rot: 0, inputs: 1, delay: 1 };
        addNode(node);
        registerDriver(a.lhs, nodeId, 0);
        nodeInputs.set(nodeId, [""]);
        errors.push(`Failed to parse assign ${a.raw}`);
      }
      continue;
    }
    if (inf.type === "VCC" || inf.type === "GND") {
      const nodeId = generateUniqueId(inf.type === "VCC" ? "vcc_" : "gnd_");
      const node: CNode = { id: nodeId, type: inf.type, x: 0, y: 0, rot: 0, inputs: 0, delay: 0 };
      addNode(node);
      registerDriver(a.lhs, nodeId, 0);
      continue;
    }
    // Handle special: For TRI, MUX etc already determined type
    // For generic gates, create node
    const nodeId = generateUniqueId(inf.type.toLowerCase() + "_");
    const node: CNode = {
      id: nodeId,
      type: inf.type,
      x: 0,
      y: 0,
      rot: 0,
      inputs: inf.inputs,
      delay: (CATALOG as any)[inf.type]?.defaultDelay ?? 1,
      // If variable fanin gates, adjust inputs property
    };
    // For gates with variable inputs like AND/OR etc, ensure inputs reflects count
    if (inf.type === "AND" || inf.type === "OR" || inf.type === "NAND" || inf.type === "NOR" || inf.type === "XOR" || inf.type === "XNOR" || inf.type === "BUS") {
      node.inputs = inf.inputs;
    }
    if (inf.type === "MUX2") node.inputs = 3;
    if (inf.type === "MUX4") node.inputs = 6;
    if (inf.type === "TRI") node.inputs = 2;
    if (inf.type === "BUFFER" || inf.type === "NOT" || inf.type === "DELAY") node.inputs = 1;

    addNode(node);
    registerDriver(a.lhs, nodeId, 0);
    nodeInputs.set(nodeId, inf.inputNets);
  }

  // Step 6: OUTPUT nodes
  const outputNodes: CNode[] = [];
  for (const outNet of outputNets) {
    // Check if there is already a node that is an output probe for this net? No, we haven't created yet.
    // Decide source net
    let sourceNet: string | null = null;
    if (outputAliasMap.has(outNet)) sourceNet = outputAliasMap.get(outNet)!;
    else if (netDriver.has(outNet)) sourceNet = outNet; // gate drives output port directly
    else if (outputExpressionSet.has(outNet) && netDriver.has(outNet)) sourceNet = outNet;
    else {
      // Check if there is an assign for this outNet that was inferred as gate and registered driver, already handled.
      // If no driver, maybe it is floating or directly not assigned
      sourceNet = null;
      if (assigns.some((a) => a.lhs === outNet && !consumedAssigns.has(assigns.indexOf(a)))) {
        // Not possible, because remaining assigns would have been handled
      }
    }
    const nodeId = generateUniqueId("out_");
    const isLed = /led/i.test(outNet);
    const type: NodeKind = isLed ? "LED" : "OUTPUT";
    const node: CNode = {
      id: nodeId,
      type,
      x: 0,
      y: 0,
      rot: 0,
      inputs: 1,
      label: outNet.replace(/_o$/, ""),
      delay: 0,
    };
    addNode(node);
    outputNodes.push(node);
    if (sourceNet) nodeInputs.set(nodeId, [sourceNet]);
    else nodeInputs.set(nodeId, [""]);
    // OUTPUT nodes are sinks, don't register driver for outNet (the outNet is already driven by gate or alias source)
    // But we need to ensure netDriver for outNet is not confused with OUTPUT node itself.
  }

  // Also need to handle case where output nets were not declared but appear as lhs of alias? Already handled.

  // Step 7: Create wires
  const wires: Wire[] = [];
  for (const node of nodes) {
    const ins = nodeInputs.get(node.id);
    if (!ins) continue;
    // For nodes like INPUT, VCC, GND etc, ins is empty
    for (let i = 0; i < ins.length; i++) {
      const src = ins[i];
      if (!src || src === "1'bx" || src === "1'bz" || src === "1'bx") continue;
      let driver: { nodeId: string; port: number } | undefined;
      if (src === "1'b1") driver = getConstDriver("1");
      else if (src === "1'b0") driver = getConstDriver("0");
      else driver = netDriver.get(src);
      if (!driver) {
        // Try to find driver via case-insensitive? keep warning
        warnings.push(`Unresolved driver for net '${src}' needed by ${node.type} ${node.label ?? node.id} port ${i}`);
        continue;
      }
      if (driver.nodeId === node.id) continue;
      const w: Wire = { id: generateUniqueId("w"), from: { node: driver.nodeId, port: driver.port }, to: { node: node.id, port: i } };
      wires.push(w);
    }
  }

  // Step 8: Auto layout
  // Build level map
  const level = new Map<string, number>();
  function computeLevel(id: string, visiting: Set<string>): number {
    if (level.has(id)) return level.get(id)!;
    if (visiting.has(id)) return 0;
    visiting.add(id);
    const ins = nodeInputs.get(id);
    let max = -1;
    if (ins) {
      for (const src of ins) {
        if (!src || src === "1'b0" || src === "1'b1" || src === "1'bx" || src === "1'bz") continue;
        let driver: { nodeId: string; port: number } | undefined;
        if (src === "1'b1" || src === "1'b0") {
          const key = src === "1'b1" ? "__VCC__" : "__GND__";
          driver = netDriver.get(key);
        } else driver = netDriver.get(src);
        if (!driver) continue;
        const dLevel = computeLevel(driver.nodeId, visiting);
        max = Math.max(max, dLevel);
      }
    }
    const my = max + 1;
    level.set(id, my);
    visiting.delete(id);
    return my;
  }
  for (const n of nodes) computeLevel(n.id, new Set());

  const byLevel = new Map<number, CNode[]>();
  for (const n of nodes) {
    const l = level.get(n.id) ?? 0;
    if (!byLevel.has(l)) byLevel.set(l, []);
    byLevel.get(l)!.push(n);
  }
  const maxL = byLevel.size ? Math.max(...byLevel.keys()) : 0;
  // Place each level column
  for (const [lvl, group] of byLevel.entries()) {
    // Sort within level for deterministic placement
    group.sort((a, b) => {
      if (a.type !== b.type) return a.type.localeCompare(b.type);
      return (a.label ?? a.id).localeCompare(b.label ?? b.id);
    });
    const colX = 80 + lvl * 220;
    // Distribute vertically: center around 300
    const spacing = 90;
    const totalH = group.length * spacing;
    const startY = 80 + Math.max(0, (600 - totalH) / 2);
    group.forEach((node, idx) => {
      // Stagger a bit for readability when many levels
      node.x = snapToGrid(colX + (idx % 2 ? 0 : 0));
      node.y = snapToGrid(startY + idx * spacing);
    });
  }
  // Ensure at least some spacing for outputs (last column)
  // If outputs are alone in last column, they will be placed there.

  // Handle isolated nodes with no level (should be 0)
  // Already placed.

  // Validation warnings
  if (!nodes.length) warnings.push("No nodes reconstructed");

  const doc: Doc = { nodes, wires, defs: [], name: modName };

  // If we failed to parse anything, provide fallback doc with error
  if (nodes.length === 0 && assigns.length === 0 && alwaysBlocks.length === 0 && inputNets.size === 0) {
    errors.push("No recognizable logic found in Verilog");
  }

  return { doc, errors, warnings };
}

// ---------------------------------------------------------------------------
// VHDL -> Circuit IR parser
// ---------------------------------------------------------------------------

export function parseVhdlHdl(source: string): ParseResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!source || !source.trim()) {
    return { doc: { nodes: [], wires: [], defs: [], name: "Untitled" }, errors: ["Empty source"], warnings };
  }

  const irDoc = tryExtractIR(source);
  if (irDoc) {
    if (!irDoc.defs) irDoc.defs = [];
    return { doc: irDoc, errors, warnings };
  }

  // Try to extract Verilog companion if present
  if (source.includes("LOGICFORGE_BEGIN") || source.includes("module") && source.includes("--")) {
    const lines = source.split("\n");
    const verilogLines: string[] = [];
    for (const l of lines) {
      const m = l.match(/^\s*--\s?(.*)$/);
      if (m) verilogLines.push(m[1]);
    }
    const verilogText = verilogLines.join("\n");
    if (/module\s+\w+/.test(verilogText)) {
      return parseVerilogHdl(verilogText);
    }
  }

  const cleaned = stripVhdlComments(source);

  // Entity
  const entityRe = /entity\s+(\w+)\s+is\s+port\s*\(([^)]*)\)\s*;/is;
  const entityMatch = cleaned.match(entityRe);
  let modName = "Imported";
  const inputNets = new Set<string>();
  const outputNets = new Set<string>();
  if (entityMatch) {
    modName = entityMatch[1];
    const portStr = entityMatch[2];
    const portRe = /(\w+)\s*:\s*(in|out)\s+std_logic/gi;
    let m: RegExpExecArray | null;
    while ((m = portRe.exec(portStr)) !== null) {
      const net = m[1];
      const dir = m[2].toLowerCase();
      if (dir === "in") inputNets.add(net);
      else outputNets.add(net);
    }
    // Fallback: split by ;
    if (!inputNets.size && !outputNets.size) {
      const parts = portStr.split(";").map((s) => s.trim()).filter(Boolean);
      for (const p of parts) {
        const mm = p.match(/(\w+)\s*:\s*(in|out)/i);
        if (!mm) continue;
        const net = mm[1];
        const dir = mm[2].toLowerCase();
        if (dir === "in") inputNets.add(net);
        else outputNets.add(net);
      }
    }
  } else {
    warnings.push("No VHDL entity found, attempting generic body parse");
  }

  // Architecture body
  let body = "";
  const archRe = /architecture\s+\w+\s+of\s+\w+\s+is([\s\S]*?)begin([\s\S]*?)end\s+architecture/is;
  const archMatch = cleaned.match(archRe);
  let declPart = "";
  if (archMatch) {
    declPart = archMatch[1];
    body = archMatch[2];
  } else {
    // Fallback: take everything after entity
    const beginIdx = cleaned.toLowerCase().indexOf("begin");
    const endIdx = cleaned.toLowerCase().lastIndexOf("end architecture");
    if (beginIdx !== -1 && endIdx !== -1) body = cleaned.slice(beginIdx + 5, endIdx);
    else body = cleaned;
  }

  // Signals (internal nets)
  const wireNets = new Set<string>();
  const regMap = new Map<string, number>(); // for vectors
  const signalRe = /signal\s+(\w+)\s*:\s*std_logic(_vector\s*\(\s*(\d+)\s+downto\s+0\s*\))?/gi;
  let m: RegExpExecArray | null;
  while ((m = signalRe.exec(declPart)) !== null) {
    const name = m[1];
    const isVector = !!m[2];
    const high = m[3] ? parseInt(m[3], 10) : 0;
    if (isVector) {
      regMap.set(name, high + 1);
      // Also treat as wire for vector signals? We'll handle.
    } else {
      wireNets.add(name);
    }
  }
  // Also handle signal declarations in body? Usually only in declPart.

  // Collect concurrent assignments:   target <= expr ;
  const assigns: { lhs: string; rhs: string }[] = [];
  const assignRe = /(\w+)(?:\s*\(\s*\d+\s*\))?\s*<=\s*([^;]+);/gi;
  while ((m = assignRe.exec(body)) !== null) {
    const lhs = m[1].trim();
    const rhs = m[2].trim();
    // Filter out assignments that are inside process? Our body is only concurrent region, but processes also have <= with sensitivity, we already excluded processes?
    // Processes contain `if` etc., but their assignments also match this regex. We need to distinguish: process assignments are inside process block, but they are sequential.
    // For now, collect all; later sequential processes will be handled via process parsing, and concurrent assigns will be filtered.
    assigns.push({ lhs, rhs });
  }

  // Collect processes for sequential logic
  const processes: { sensitivity: string; body: string }[] = [];
  const procRe = /process\s*\(\s*([^)]+)\s*\)\s*begin([\s\S]*?)end\s+process\s*;/gi;
  while ((m = procRe.exec(body)) !== null) {
    processes.push({ sensitivity: m[1].trim(), body: m[2].trim() });
  }
  // Also handle process without sensitivity? ignore.

  // Now we need to interpret assigns and processes to create nodes.
  // For simplicity, we can convert VHDL expressions to Verilog-ish and reuse Verilog infer logic.
  // Map VHDL operators to Verilog symbols for inference.
  function vhdlToVerilogExpr(expr: string): string {
    let e = expr;
    // Remove single quotes for logic values? `'1'` -> 1'b1 etc? Convert.
    e = e.replace(/'1'/g, "1'b1").replace(/'0'/g, "1'b0").replace(/'Z'/g, "1'bz").replace(/'X'/g, "1'bx");
    // Replace VHDL operators with Verilog equivalents
    // Note order: handle longer first
    e = e.replace(/\bxnor\b/gi, " ^~ "); // temporary, will be normalized via pattern? Simpler: treat xnor as ~^
    // Actually for inference we map to & | ^ with negation wrapper. So convert:
    // `not (A and B)` -> `~(A & B)` ; `A nand B` -> `~(A & B)`
    // So handle `nand`, `nor`, `xnor` etc.
    // Replace `nand` => `~&` style? We'll convert `A nand B` -> `~(A & B)`
    e = e.replace(/(\w+)\s+nand\s+(\w+)/gi, "~($1 & $2)");
    e = e.replace(/(\w+)\s+nor\s+(\w+)/gi, "~($1 | $2)");
    e = e.replace(/(\w+)\s+xnor\s+(\w+)/gi, "~($1 ^ $2)");
    // Replace remaining `and` `or` `xor`
    e = e.replace(/\band\b/gi, "&");
    e = e.replace(/\bor\b/gi, "|");
    e = e.replace(/\bxor\b/gi, "^");
    // Replace `not` -> ~
    e = e.replace(/\bnot\b/gi, "~");
    // Replace `when ... else` for mux2: `A when S='1' else B` -> `S ? A : B` ? Our Verilog mux2 is S ? I1 : I0 . VHDL `Y <= I1 when S='1' else I0` -> `S ? I1 : I0`
    // Handle `X when S='1' else Y` pattern
    e = e.replace(/(\w+)\s+when\s+(\w+)\s*=\s*'1'\s*else\s+(\w+)/gi, "$2 ? $1 : $3");
    e = e.replace(/(\w+)\s+when\s+(\w+)\s*=\s*'0'\s*else\s+(\w+)/gi, "$2 ? $3 : $1");
    // For vector select like `with S select` not handled.
    // Remove extra parentheses noise
    e = e.replace(/"/g, "");
    return e;
  }

  // For processes, we need to deduce sequential type.
  // Simplify: process with sensitivity `CLK, RST` and body containing `if RST='1'` and `elsif rising_edge(CLK)` and `Q <= D` -> DFF
  // We'll create Verilog-style always blocks from processes and reuse Verilog sequential parsing.

  // Build a Verilog-like text from VHDL processes + assigns and then delegate to Verilog parser?
  // Instead of duplicating logic, we can synthesize a Verilog text from VHDL structure: create a Verilog module header with same ports, emit assigns as Verilog assigns after converting expressions, and emit always blocks from processes.

  // Simpler: Construct a pseudo-Verilog source string that our Verilog parser can handle, using the same port names, signals, assigns.
  let pseudoVerilog = `module ${modName} (\n`;
  const portLines: string[] = [];
  for (const n of inputNets) portLines.push(`  input ${n}`);
  for (const n of outputNets) portLines.push(`  output ${n}`);
  pseudoVerilog += portLines.join(",\n") + "\n);\n";
  // Declare wires and regs
  for (const w of wireNets) pseudoVerilog += `  wire ${w};\n`;
  for (const [reg, bits] of regMap) {
    if (bits > 1) pseudoVerilog += `  reg [${bits - 1}:0] ${reg};\n`;
    else pseudoVerilog += `  wire ${reg};\n`;
  }
  // Concurrent assigns -> Verilog assigns
  // Filter out those that are inside processes? Our assigns collection included all `<=`. We need to exclude those inside processes (they are sequential). So we should only add concurrent assigns that are not inside a process body string.
  // Determine which assigns are inside processes by checking if their lhs appears inside a process body assignment pattern.
  // For now, we add all assigns as concurrent, but process bodies will be handled as always blocks, may cause duplication.
  // We'll collect concurrent assigns as those where lhs is not a reg driven by process? Heuristic: if lhs is a signal that is assigned inside a process (like Q), then its driver is process, not concurrent. So we can skip concurrent assigns where lhs appears as target in any process.

  const processTargets = new Set<string>();
  for (const proc of processes) {
    // Find all `sig <=` inside process body
    const innerRe = /(\w+)\s*<=\s*[^;]+;/g;
    let mm: RegExpExecArray | null;
    while ((mm = innerRe.exec(proc.body)) !== null) {
      processTargets.add(mm[1]);
    }
  }
  for (const a of assigns) {
    // If this assign's lhs is a process target and the assign appears inside a process, skip it here (it will be handled via always block)
    if (processTargets.has(a.lhs) && processes.some((p) => p.body.includes(`${a.lhs} <=`))) continue;
    // Convert VHDL rhs to Verilog rhs
    const vRhs = vhdlToVerilogExpr(a.rhs);
    pseudoVerilog += `  assign ${a.lhs} = ${vRhs};\n`;
  }
  // Processes -> always blocks (Verilog style)
  for (const proc of processes) {
    const sens = proc.sensitivity;
    const isClocked = /rising_edge/i.test(proc.body) || sens.toLowerCase().includes("clk");
    if (isClocked) {
      // Extract CLK and RST
      const clkM = sens.match(/(\w+)/);
      const clk = clkM ? clkM[1] : "CLK";
      // Find RST: look for `if RST` in body
      const rstM = proc.body.match(/if\s+(\w+)\s*=\s*'1'/i);
      const rst = rstM ? rstM[1] : null;
      // Determine type: check for case (JKFF), else if (TFF), else DFF etc.
      // For simplicity, generate an always block that Verilog parser can recognize as DFF
      // Find the main assignment: `Q <= D` inside rising edge
      const qDMatch = proc.body.match(/rising_edge\s*\(\s*(\w+)\s*\)\s*then\s*(\w+)\s*<=\s*(\w+)/i);
      if (qDMatch) {
        const q = qDMatch[2], d = qDMatch[3];
        if (rst) {
          pseudoVerilog += `  always @(posedge ${clk} or posedge ${rst}) begin\n    if (${rst}) ${q} <= 1'b0; else ${q} <= ${d};\n  end\n`;
          // Need Qn assign if present elsewhere: check for `QN <= not Q`
          const qnMatch = proc.body.match(/(\w+)\s*<=\s*not\s+(\w+)/i);
          if (qnMatch && qnMatch[2] === q) {
            pseudoVerilog += `  assign ${qnMatch[1]} = ~${q};\n`;
          } else {
            // Also check concurrent assign for Qn outside process
            const concQn = assigns.find((a) => a.rhs.match(new RegExp(`not\\s+${q}`, "i")));
            if (concQn) {
              const vRhs = vhdlToVerilogExpr(concQn.rhs);
              pseudoVerilog += `  assign ${concQn.lhs} = ${vRhs};\n`;
            }
          }
        } else {
          pseudoVerilog += `  always @(posedge ${clk}) begin\n    ${q} <= ${d};\n  end\n`;
        }
        continue;
      }
      // For counter: `REG <= REG + 1`
      if (proc.body.includes("+ 1") || proc.body.includes("+1")) {
        const regM = proc.body.match(/(\w+)\s*<=\s*std_logic_vector\s*\(\s*unsigned\s*\(\s*(\w+)\s*\)\s*\+\s*1\s*\)/i);
        const regName = regM ? regM[1] : [...regMap.keys()][0] ?? "cnt_reg";
        const bits = regMap.get(regName) ?? 4;
        // Need to declare reg already
        if (rst) {
          pseudoVerilog += `  always @(posedge ${clk} or posedge ${rst}) begin\n    if (${rst}) ${regName} <= ${bits}'d0; else ${regName} <= ${regName} + 1'b1;\n  end\n`;
        } else {
          pseudoVerilog += `  always @(posedge ${clk}) begin\n    ${regName} <= ${regName} + 1'b1;\n  end\n`;
        }
        // Add bit assigns
        for (let i = 0; i < bits; i++) {
          pseudoVerilog += `  assign ${regName}_q${i} = ${regName}[${i}];\n`; // but original VHDL may have Q0 <= reg(0) etc.
          // If original had assignments for bits, they were already in assigns; but we already filtered them? Need to handle.
        }
        continue;
      }
      // Fallback: emit as generic always
      pseudoVerilog += `  always @(*) begin\n    // ${proc.body.slice(0, 80)} \n  end\n`;
    } else {
      // Latch: `if EN then Q <= D`
      const latchM = proc.body.match(/if\s+(\w+)\s*=\s*'1'\s*then\s*(\w+)\s*<=\s*(\w+)/i);
      if (latchM) {
        const en = latchM[1], q = latchM[2], d = latchM[3];
        pseudoVerilog += `  always @(*) if (${en}) ${q} = ${d};\n`;
        pseudoVerilog += `  assign ${q}_n = ~${q};\n`;
        continue;
      }
    }
  }
  pseudoVerilog += `\nendmodule\n`;

  // Now delegate to Verilog parser
  const res = parseVerilogHdl(pseudoVerilog);
  // Override name with original VHDL entity name
  res.doc.name = modName;
  // Merge warnings/errors
  res.warnings.push(...warnings);
  res.errors.push(...errors);
  return res;
}

// ---------------------------------------------------------------------------
// Generic HDL wrapper
// ---------------------------------------------------------------------------

export function parseHardwareDescriptionLanguage(source: string): ParseResult {
  const trimmed = source.trim();
  // Auto-detect: VHDL keywords vs Verilog
  const isVhdl = /^\s*library\s+ieee/i.test(trimmed) || /entity\s+\w+\s+is/i.test(trimmed) || /architecture\s+\w+\s+of/i.test(trimmed);
  const isVerilog = /module\s+\w+/i.test(trimmed);
  if (isVhdl && !isVerilog) return parseVhdlHdl(source);
  if (isVerilog && !isVhdl) return parseVerilogHdl(source);
  // If both or ambiguous, try Verilog first, fallback to VHDL
  const vRes = parseVerilogHdl(source);
  if (vRes.doc.nodes.length > 0) return vRes;
  return parseVhdlHdl(source);
}

// Convenience wrappers for bidirectional conversion
export function convertHdlToCircuit(source: string): Doc {
  const res = parseHardwareDescriptionLanguage(source);
  if (res.errors.length && !res.doc.nodes.length) {
    throw new Error(`HDL parse failed: ${res.errors.join("; ")}`);
  }
  return res.doc;
}

export function convertCircuitToHdl(doc: Doc, lang: "verilog" | "vhdl" = "verilog"): string {
  return lang === "vhdl" ? generateVhdl(doc) : generateVerilog(doc);
}

// Keep download helpers
export function downloadTextFile(filename: string, text: string, mime = "text/plain") {
  const blob = new Blob([text], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export function downloadJsonFile(filename: string, data: unknown) {
  downloadTextFile(filename, JSON.stringify(data, null, 2), "application/json");
}


// ---------------------------------------------------------------------------
// Legacy aliases — keep old short/random names for backward compatibility
// ---------------------------------------------------------------------------
export const ident = sanitizeIdentifier;
export const uniq = generateUniqueName;
export const netId = getOrCreateNetIdentifier;
export const emitVerilog = generateVerilog;
export const emitVhdl = generateVhdl;
export const parseVerilog = parseVerilogHdl;
export const parseVhdl = parseVhdlHdl;
export const parseHdl = parseHardwareDescriptionLanguage;
export const hdlToCircuit = convertHdlToCircuit;
export const circuitToHdl = convertCircuitToHdl;
export const downloadText = downloadTextFile;
export const downloadJson = downloadJsonFile;

