import { type Doc, isGate, isSequential, nodeTitle, specOf } from "./circuit";

function ident(raw: string) {
  let t = raw.replace(/[^A-Za-z0-9_]/g, "_");
  if (!t) t = "n";
  if (/^[0-9]/.test(t)) t = "n_" + t;
  return t;
}

function uniq(base: string, used: Set<string>) {
  let s = ident(base);
  let i = 2;
  while (used.has(s)) s = `${ident(base)}_${i++}`;
  used.add(s);
  return s;
}

function netId(nodeId: string, port: number, used: Set<string>, cache: Map<string, string>, hint: string) {
  const k = `${nodeId}:${port}`;
  const hit = cache.get(k);
  if (hit) return hit;
  const name = uniq(hint, used);
  cache.set(k, name);
  return name;
}

export function emitVerilog(doc: Doc): string {
  const { nodes, wires, defs } = doc;
  const used = new Set<string>(["module", "input", "output", "wire", "assign", "always", "begin", "end", "posedge"]);
  const cache = new Map<string, string>();
  const title = (nId: string) => {
    const n = nodes.find((x) => x.id === nId);
    return n ? nodeTitle(n, defs) : nId;
  };

  const inputs = nodes.filter((n) => n.type === "INPUT" || n.type === "CLOCK");
  const outputs = nodes.filter((n) => n.type === "OUTPUT" || n.type === "LED");

  for (const n of nodes) {
    const sp = specOf(n, defs);
    sp.outs.forEach((nm, i) => netId(n.id, i, used, cache, `${title(n.id)}_${nm}`));
    if (n.type === "INPUT" || n.type === "CLOCK") netId(n.id, 0, used, cache, title(n.id));
  }

  const inPorts = inputs.map((n) => netId(n.id, 0, used, cache, title(n.id)));
  const outPorts = outputs.map((n) => {
    const nm = uniq(title(n.id) + "_o", used);
    cache.set(`probe:${n.id}`, nm);
    return nm;
  });

  const portList = [...inPorts.map((p) => `  input  ${p}`), ...outPorts.map((p) => `  output ${p}`)].join(",\n");
  const lines: string[] = [];
  const mod = ident(doc.name || "LogicForge");
  lines.push(`// Generated by LogicForge`);
  lines.push(`module ${mod} (`);
  lines.push(portList || "  // no ports");
  lines.push(");");
  lines.push("");

  const driven = new Set(inPorts);
  for (const n of nodes) {
    const sp = specOf(n, defs);
    for (let i = 0; i < sp.outs.length; i++) {
      const nm = netId(n.id, i, used, cache, `${title(n.id)}_${sp.outs[i]}`);
      if (!driven.has(nm) && !inPorts.includes(nm)) {
        lines.push(`  wire ${nm};`);
        driven.add(nm);
      }
    }
  }
  lines.push("");

  const srcOf = (node: string, port: number) => {
    const w = wires.find((x) => x.to.node === node && x.to.port === port);
    if (!w) return "1'bx";
    return netId(w.from.node, w.from.port, used, cache, title(w.from.node));
  };

  for (const n of nodes) {
    const sp = specOf(n, defs);
    const y = (i = 0) => netId(n.id, i, used, cache, `${title(n.id)}_${sp.outs[i] ?? "Y"}`);
    const a = (i: number) => srcOf(n.id, i);
    if (n.type === "INPUT" || n.type === "CLOCK") continue;
    if (n.type === "VCC") { lines.push(`  assign ${y()} = 1'b1;`); continue; }
    if (n.type === "GND") { lines.push(`  assign ${y()} = 1'b0;`); continue; }
    if (n.type === "OUTPUT" || n.type === "LED") {
      const p = cache.get(`probe:${n.id}`);
      if (p) lines.push(`  assign ${p} = ${a(0)};`);
      continue;
    }
    if (isGate(n.type) || n.type === "DELAY") {
      const ins = sp.ins.map((_, i) => a(i));
      const expr =
        n.type === "AND" || n.type === "NAND" ? ins.join(" & ") :
        n.type === "OR" || n.type === "NOR" ? ins.join(" | ") :
        n.type === "XOR" || n.type === "XNOR" ? ins.join(" ^ ") :
        ins[0] ?? "1'bx";
      const wrap = n.type === "NAND" || n.type === "NOR" || n.type === "XNOR" || n.type === "NOT" ? `~(${expr})` : expr;
      lines.push(`  assign ${y()} = ${wrap};`);
      continue;
    }
    if (n.type === "TRI") { lines.push(`  assign ${y()} = ${a(1)} ? ${a(0)} : 1'bz;`); continue; }
    if (n.type === "BUS") { lines.push(`  assign ${y()} = ${sp.ins.map((_, i) => a(i)).join(" | ")};`); continue; }
    if (n.type === "PULLUP") { lines.push(`  assign ${y()} = ${a(0)};`); continue; }
    if (n.type === "PULLDOWN") { lines.push(`  assign ${y()} = ${a(0)};`); continue; }
    if (n.type === "MUX2") { lines.push(`  assign ${y()} = ${a(2)} ? ${a(1)} : ${a(0)};`); continue; }
    if (n.type === "MUX4") {
      lines.push(`  assign ${y()} = ({${a(5)},${a(4)}} == 2'b00) ? ${a(0)} : ({${a(5)},${a(4)}} == 2'b01) ? ${a(1)} : ({${a(5)},${a(4)}} == 2'b10) ? ${a(2)} : ${a(3)};`);
      continue;
    }
    if (n.type === "DEC2") {
      for (let i = 0; i < 4; i++) {
        const aa = i & 1 ? a(0) : `~${a(0)}`;
        const bb = i & 2 ? a(1) : `~${a(1)}`;
        lines.push(`  assign ${y(i)} = ${aa} & ${bb};`);
      }
      continue;
    }
    if (n.type === "ADDER") {
      lines.push(`  assign ${y(0)} = ${a(0)} ^ ${a(1)} ^ ${a(2)};`);
      lines.push(`  assign ${y(1)} = (${a(0)} & ${a(1)}) | (${a(2)} & (${a(0)} ^ ${a(1)}));`);
      continue;
    }
    if (n.type === "DFF") {
      lines.push(`  always @(posedge ${a(1)} or posedge ${a(2)}) begin`);
      lines.push(`    if (${a(2)}) ${y(0)} <= 1'b0; else ${y(0)} <= ${a(0)};`);
      lines.push(`  end`);
      lines.push(`  assign ${y(1)} = ~${y(0)};`);
      continue;
    }
    if (n.type === "TFF") {
      lines.push(`  always @(posedge ${a(1)} or posedge ${a(2)}) begin`);
      lines.push(`    if (${a(2)}) ${y(0)} <= 1'b0; else if (${a(0)}) ${y(0)} <= ~${y(0)};`);
      lines.push(`  end`);
      lines.push(`  assign ${y(1)} = ~${y(0)};`);
      continue;
    }
    if (n.type === "JKFF") {
      lines.push(`  always @(posedge ${a(2)} or posedge ${a(3)}) begin`);
      lines.push(`    if (${a(3)}) ${y(0)} <= 1'b0;`);
      lines.push(`    else case ({${a(0)}, ${a(1)}})`);
      lines.push(`      2'b10: ${y(0)} <= 1'b1; 2'b01: ${y(0)} <= 1'b0; 2'b11: ${y(0)} <= ~${y(0)};`);
      lines.push(`    endcase`);
      lines.push(`  end`);
      lines.push(`  assign ${y(1)} = ~${y(0)};`);
      continue;
    }
    if (n.type === "DLATCH") {
      lines.push(`  always @(*) if (${a(1)}) ${y(0)} = ${a(0)};`);
      lines.push(`  assign ${y(1)} = ~${y(0)};`);
      continue;
    }
    if (n.type === "COUNTER") {
      const bits = Math.min(8, Math.max(2, n.bits ?? 4));
      const qn = uniq(title(n.id) + "_reg", used);
      lines.push(`  reg [${bits - 1}:0] ${qn};`);
      lines.push(`  always @(posedge ${a(0)} or posedge ${a(1)}) begin`);
      lines.push(`    if (${a(1)}) ${qn} <= ${bits}'d0; else ${qn} <= ${qn} + 1'b1;`);
      lines.push(`  end`);
      for (let i = 0; i < bits; i++) lines.push(`  assign ${y(i)} = ${qn}[${i}];`);
      continue;
    }
    if (n.type === "CUSTOM") lines.push(`  // hierarchical ${title(n.id)}`);
  }

  if (nodes.some((n) => isSequential(n.type))) {
    lines.splice(5, 0, "  // Sequential Q ports are driven from always blocks.");
  }

  lines.push("");
  lines.push("endmodule");
  lines.push("");
  return lines.join("\n");
}

export function emitVhdl(doc: Doc): string {
  const v = emitVerilog(doc);
  const mod = ident(doc.name || "LogicForge");
  const ins = doc.nodes.filter((n) => n.type === "INPUT" || n.type === "CLOCK");
  const outs = doc.nodes.filter((n) => n.type === "OUTPUT" || n.type === "LED");
  const ports = [
    ...ins.map((n) => `    ${ident(nodeTitle(n, doc.defs))} : in  std_logic`),
    ...outs.map((n) => `    ${ident(nodeTitle(n, doc.defs))} : out std_logic`),
  ].join(";\n");
  return [
    `-- Generated by LogicForge`,
    `library ieee;`,
    `use ieee.std_logic_1164.all;`,
    `use ieee.numeric_std.all;`,
    ``,
    `entity ${mod} is`,
    `  port (`,
    ports || "    -- no ports",
    `  );`,
    `end entity;`,
    ``,
    `-- See Verilog companion for the synthesizable netlist.`,
    v.split("\n").map((l) => "-- " + l).join("\n"),
    ``,
    `architecture rtl of ${mod} is`,
    `begin`,
    `end architecture;`,
    ``,
  ].join("\n");
}

export function downloadText(filename: string, text: string, mime = "text/plain") {
  const blob = new Blob([text], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export function downloadJson(filename: string, data: unknown) {
  downloadText(filename, JSON.stringify(data, null, 2), "application/json");
}
